context:
  name: arena
  version: 0.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: .

build:
  number: 0
  script: |
    unset CFLAGS CXXFLAGS
    cmake $CMAKE_ARGS -S . -B build -DCMAKE_BUILD_TYPE=Release
    cmake --build build --target install

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - gtest
    - booster_robotics_sdk ==1.5.0
    - eigen
    - onnxruntime-cpp ==1.24.2
    - msgpack-cxx
    - mujoco >=3.0
    - glfw
    - tinyxml2
    - boost-cpp
    - libgl-devel
    - libegl-devel
    - if: target_platform == "linux-64"
      then: sysroot_linux-64 >=2.39
    - if: target_platform == "linux-aarch64"
      then: sysroot_linux-aarch64 >=2.39
  run:
    - booster_robotics_sdk ==1.5.0
    - onnxruntime-cpp ==1.24.2
    - mujoco >=3.0
    - glfw
    - tinyxml2
    - msgpack-cxx

about:
  summary: Gladius project for robotics simulation and control.
  license: MIT
